feat: deploy graphql-server
kubeagi/arcadia pull request #186
Opened 2023-11-07 07:44 UTC by zqq454224016

#### What type of PR is this?

#### What this PR does / why we need it

#### Which issue(s) this PR fixes

Fixes #

#### Special notes for your reviewer

2023-11-07 08:00 UTC, bjwswang commented on charts/arcadia/templates/portal.yaml
> +
清理下空格

2023-11-07 08:01 UTC, bjwswang commented on charts/arcadia/templates/portal.yaml
> +            - "--client-id={{ .Values.portal.clientID}}"
这几个参数都是enable-oidc后必须要填写的，应该放到 if end 里边

2023-11-07 08:03 UTC, bjwswang commented on charts/arcadia/values.yaml
> +  enableoidc: false
这几个参数都是oidc相关。应该这样配置:
```yaml
portal:
  enabled: false
  oidc:
     enabled: false
     clientID: bff-client
     issuerURL: https://portal.172.22.96.167.nip.io/oidc
     clientSecret: 61324af0-1234-4f61-b110-ef57013267d6
     masterURL: https://k8s.172.22.96.167.nip.io
```

2023-11-07 08:03 UTC, bjwswang commented on charts/arcadia/templates/portal.yaml
> +apiVersion: apps/v1
结合 values里边的 portal.enabled 判断是否应该安装portal

2023-11-07 08:03 UTC, bjwswang requested changes
修改

2023-11-07 09:07 UTC, bjwswang commented on charts/arcadia/templates/portal.yaml
> +        - name: portal-controller
`portal-controller` -> `server`

2023-11-07 09:08 UTC, bjwswang commented on charts/arcadia/templates/portal.yaml
> +          {{- if .Values.portal.oidc.enableoidc -}}
还有另外一个是否启用playground的参数丢了

2023-11-07 09:08 UTC, bjwswang commented on charts/arcadia/templates/portal.yaml
> +  name: bff-server
`bff-server` -> `portal-server`

2023-11-07 09:10 UTC, bjwswang commented on charts/arcadia/templates/portal.yaml
> +    - host: localhost
参考 fastchat 的配置方法 https://github.com/kubeagi/arcadia/blob/main/charts/arcadia/charts/fastchat/templates/ingress.yaml#L39

这里的host和service都应该是根据名称可配置

2023-11-07 09:11 UTC, bjwswang commented on charts/arcadia/templates/portal.yaml
> +  name: protal-ingress
{{ .Release.Name }}-portal-ingress

2023-11-08 05:16 UTC, bjwswang commented on charts/arcadia/templates/portal.yaml
> +            - "/graphql-server --enablep-layground={{ .Values.portal.enableplayground }}"
if {{ .Values.portal.enableplayground }} 
   - "-enable-palyground"
{{- end }}

2023-11-08 05:17 UTC, bjwswang commented on charts/arcadia/templates/portal.yaml
> +          {{- if .Values.portal.oidc.enableoidc -}}
```yaml
{{- if  .Values.portal.oidc. enableoidc -}} 
   - "-enable-oidc"
   - "-client-id=xxx"
   - xxx
{{- end }}
```

2023-11-08 05:17 UTC, bjwswang requested changes
Command写的不对

2023-11-08 08:22 UTC, Abirdcfly commented on charts/arcadia/templates/portal.yaml
> +  name: portal-server
```suggestion
  name: {{ .Release.Name }}-portal-server
  namespace: {{ .Release.Namespace }}
```

2023-11-08 08:23 UTC, Abirdcfly commented on charts/arcadia/templates/portal.yaml
> +  name: {{ .Release.Name }}-portal-ingress
```suggestion
  name: {{ .Release.Name }}-portal-ingress
  namespace: {{ .Release.Namespace }}
```

2023-11-08 08:48 UTC, merged