chore: optimize graphql-server chart
kubeagi/arcadia pull request #195
Opened 2023-11-09 07:13 UTC by 0xff-dev

#### What type of PR is this?
/kind bug

#### What this PR does / why we need it
chore: optimize graphql-server chart

#### Which issue(s) this PR fixes

Fixes #

#### Special notes for your reviewer

2023-11-09 07:20 UTC, Abirdcfly approved these changes

2023-11-09 08:57 UTC, bjwswang requested changes
fix the conflicts

2023-11-13 02:00 UTC, bjwswang commented on charts/arcadia/values.yaml
>      enableoidc: false
enableoidc -> `enabled`

2023-11-13 02:11 UTC, bjwswang approved these changes

2023-11-13 03:26 UTC, merged