feat: dataset and versioneddataset impl
kubeagi/arcadia pull request #208
Opened 2023-11-15 09:47 UTC by 0xff-dev

#### What type of PR is this?
/kind feature

#### What this PR does / why we need it
feat: dataset and versioneddataset impl

#### Which issue(s) this PR fixes

Fixes #

#### Special notes for your reviewer

2023-11-15 11:14 UTC, bjwswang requested changes
fix the golangci-lint errors

2023-11-16 02:11 UTC, bjwswang commented on api/v1alpha1/dataset.go
> +	LabelDatasetFinalizer = Group + "/finalizers"
we have a common finalizer label at https://github.com/kubeagi/arcadia/blob/main/api/v1alpha1/common.go#L25

2023-11-16 02:18 UTC, bjwswang commented on api/v1alpha1/versioneddataset.go
> +		_, _ = fmt.Sscanf(datasource, "%s %s", &namespace, &name)
@0xff-dev what is this line for ?

2023-11-16 02:39 UTC, 0xff-dev commented on api/v1alpha1/versioneddataset.go
> +		_, _ = fmt.Sscanf(datasource, "%s %s", &namespace, &name)
Get namespace and name.

2023-11-16 02:59 UTC, bjwswang approved these changes

2023-11-16 03:00 UTC, Abirdcfly approved these changes

2023-11-16 03:19 UTC, merged