when the task fails, update the 'message' information in the dataset …
kubeagi/arcadia pull request #562
Opened 2024-01-15 09:12 UTC by wangxinbiao

#### What type of PR is this?

/kind feature

#### What this PR does / why we need it

when the task fails, update the 'message' information in the dataset
In the generated CSV, add information such as 'file_name,' 'page_number,' and 'chunk_content.

#### Which issue(s) this PR fixes

Fixes #558 

#### Special notes for your reviewer

2024-01-15 10:11 UTC, bjwswang commented on data-processing/data_manipulation/data_store_process/minio_store_process.py
> +        namespace=req_json['namespace'],
这个namespace怎么设置的？ 参数为什么从 bucket_name变更成了 namespace

2024-01-15 10:21 UTC, wangxinbiao commented on data-processing/data_manipulation/data_store_process/minio_store_process.py
> +        namespace=req_json['namespace'],
因为一开始的时候没让前端传namespace字段信息，但是沟通的是bucket_name和namespace是同一个值，当时就直接用前端传的bucket_name字段的值。后面前端传了namespace的值了，现在我就直接变更为namespace了。

2024-01-16 03:33 UTC, bjwswang commented on data-processing/data_manipulation/data_store_process/minio_store_process.py
> +        namespace=req_json['namespace'],
那 bucket_name这字段还在request里吗？ 这两个实际上是完全一样，保留一个即可

2024-01-16 03:34 UTC, bjwswang commented on data-processing/data_manipulation/data_store_process/minio_store_process.py
> +        message='',
这里是否可以考虑加一个有意义的默认信息？ 比如简单的`Data is processing` 。

2024-01-16 03:54 UTC, wangxinbiao commented on data-processing/data_manipulation/data_store_process/minio_store_process.py
> +        namespace=req_json['namespace'],
存在，bucket_name这个字段用于minio那部分

2024-01-16 04:15 UTC, bjwswang commented on data-processing/data_manipulation/data_store_process/minio_store_process.py
> +        namespace=req_json['namespace'],
保留一个即可

2024-01-16 05:33 UTC, bjwswang requested changes
修复下

2024-01-16 05:46 UTC, wangxinbiao commented on data-processing/data_manipulation/data_store_process/minio_store_process.py
> +        namespace=req_json['namespace'],
好的

2024-01-16 05:46 UTC, wangxinbiao commented on data-processing/data_manipulation/data_store_process/minio_store_process.py
> +        message='',
好的

2024-01-16 07:08 UTC, wangxinbiao commented
> 修复下

@bjwswang 已修复

2024-01-16 07:17 UTC, bjwswang commented on apiserver/graph/schema/dataprocessing.graphqls
> -  bucket_name: String!
@wangxinbiao 和前端协同确认下，这个bucket_name全部替换成了namespace。

2024-01-16 07:18 UTC, bjwswang commented on deploy/charts/arcadia/templates/pg-init-data-configmap.yaml
>              current_log_id character varying(32) COLLATE pg_catalog."default",
@wangxinbiao  Need to bump chart version

2024-01-16 07:34 UTC, wangxinbiao commented on apiserver/graph/schema/dataprocessing.graphqls
> -  bucket_name: String!
已沟通过

2024-01-16 07:40 UTC, wangxinbiao commented on deploy/charts/arcadia/templates/pg-init-data-configmap.yaml
>              current_log_id character varying(32) COLLATE pg_catalog."default",
这个是什么意思？

2024-01-16 08:22 UTC, bjwswang commented on deploy/charts/arcadia/templates/pg-init-data-configmap.yaml
>              current_log_id character varying(32) COLLATE pg_catalog."default",
升级下Chart版本。

2024-01-16 09:24 UTC, bjwswang approved these changes

2024-01-16 09:24 UTC, merged