feat:deduplicate QA
kubeagi/arcadia pull request #702
Opened 2024-02-01 08:41 UTC by wangxinbiao

#### What type of PR is this?

#### What this PR does / why we need it

feat: Remove duplicate QA data.
chore: Optimized code for chunk and handle sections.

#### Which issue(s) this PR fixes

Fixes #431

#### Special notes for your reviewer

2024-02-01 10:25 UTC, bjwswang commented
@wangxinbiao please work with frontend on this enhancement.

2024-02-01 10:25 UTC, bjwswang commented on pypi/data-processing/src/document_chunks/spacy_text_splitter.py
> +# Copyright 2023 KubeAGI.
2023 v-> 2024

2024-02-02 01:49 UTC, bjwswang requested changes
see the comments

2024-02-02 03:01 UTC, wangxinbiao commented on pypi/data-processing/src/document_chunks/spacy_text_splitter.py
> +# Copyright 2023 KubeAGI.
Corrected

2024-02-02 05:32 UTC, bjwswang approved these changes

2024-02-02 05:32 UTC, merged