feat: add a new api to get rag evaluation report
kubeagi/arcadia pull request #704
Opened 2024-02-01 08:55 UTC by 0xff-dev

#### What type of PR is this?
/kind feature

#### What this PR does / why we need it
feat: add a new api to get rag evaluation report

#### Which issue(s) this PR fixes

Fix https://github.com/kubeagi/arcadia/issues/684

#### Special notes for your reviewer

2024-02-02 02:08 UTC, bjwswang commented on apiserver/pkg/rag/report.go
> +	metricChinese = map[string]string{
also metricEnglish

2024-02-02 02:08 UTC, bjwswang commented on apiserver/pkg/rag/report.go
> +	summarySuggestionTemplate = `通过此次评估，您的智能体得分偏低，主要体现在 <strong>%s</strong> 这 %d 项指标得分偏低。
summarySuggestionTemplateInEng

2024-02-02 02:09 UTC, bjwswang commented on apiserver/pkg/rag/report.go
> +	metricThresholds map[string]float64) (Report, error) {
A new parameter `language`

2024-02-02 02:10 UTC, bjwswang requested changes
@0xff-dev we only provide the summary data. Let the front-end decides how to use them.

2024-02-19 09:32 UTC, 0xff-dev commented
For the English message, I think it can be implemented in the next version

2024-02-19 09:59 UTC, merged